//autogenerated by util.build.BuildDalvikSuite, do not change
package dot.junit.opcodes.move_exception;
import dot.junit.opcodes.move_exception.d.*;
import dot.junit.*;
public class Main_testN1 extends DxAbstractMain {
    public static void main(String[] args) throws Exception {
        T_move_exception_1 t = new T_move_exception_1();
        try {
            t.run();
            fail("ArithmeticException was not thrown");
        } catch (ArithmeticException ae) {
            //expected
        } catch (Exception ex) {
            fail("Exception " + ex + " was thrown instead off ArithmeticException");
        }
    }
}
